[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
ClientMonitor = 15000
Host = '10.0.0.75'
Port = 50001
Protocol = 'http'
StartupMsg = 'device rfrain started'
Timeout = 5000
ConnectRetries = 10
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = ''

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = './res'
  UpdateLastConnected = false

# Pre-define Devices
[[DeviceList]]
  Name = 'Time-Sensor-01'
  Profile = 'Time-Sensor'
  Description = 'device reporting time in seconds'
  Labels = [ 'time-sensor' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
    Address = 'simple01'
    Port = '300'
  [[DeviceList.AutoEvents]]
    Frequency = '10s'
    OnChange = false
    Resource = 'Time_Seconds'

[Driver]
User="customer@iotechsys.com"
Password="customer@iotechsys.com!"
Company="iotechsys"
SessionKeyURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/get_sessionkey"
StartMonitoringJitterURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/start_monitoring_new_tags_jitter"
GetTagsJitterURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/get_latest_tags_jitter"
