[Writable]
LogLevel = 'INFO'

[Service]
BootTimeout = 30000
CheckInterval = '10s'
ClientMonitor = 15000
Host = '10.0.0.75'
Port = 50001
Protocol = 'http'
StartupMsg = 'device rfrain started'
Timeout = 5000
ConnectRetries = 10
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Logging]
EnableRemote = false
File = ''

[Clients]
  [Clients.Data]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48080

  [Clients.Metadata]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48081

  [Clients.Logging]
  Protocol = 'http'
  Host = 'localhost'
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ''
  InitCmdArgs = ''
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ''
  RemoveCmdArgs = ''
  ProfilesDir = './res'
  UpdateLastConnected = false

# Pre-define Devices
[[DeviceList]]
  Name = 'IOTECH0A0B0C'
  Profile = 'RFRainSensor'
  Description = 'RFRain RFID sensor reader'
  Labels = [ 'RFID-sensor' ]
  [DeviceList.Protocols]
    [DeviceList.Protocols.other]
    Address = 'simple01'
    Port = '300'
  [[DeviceList.AutoEvents]]
    Frequency = '10s'
    OnChange = false
    Resource = 'Latest_Tags'

[Driver]
User="customer@iotechsys.com"
Password="customer@iotechsys.com!"
Company="iotechsys"
SessionKeyURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/get_sessionkey"
StartMonitoringURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/start_monitoring_new_tags_history"
GetTagsURL="https://cd2.rfrain.com/ZoneManager/rfrainapi.php/get_latest_tags_history"
InvalidateURL="https://cd2.rfrain.com/rfrainapi.php/destroy_sessionkey"